### ISSUE TITLE
Error with go 1.12

### ISSUE THREAD

**Issue by ulrichSchreiner** [go4org/go4#43]
hi,

i tried to compile my code with the today released go1.12 but get an error:
~~~
go4.org/reflectutil.typedmemmove: relocation target runtime.typedmemmove not defined for ABI0 (but is defined for ABIInternal)
~~~

`go4.org` seems to be a transitive dependency which does not compile with go1.12.

or should i report this to the golang tracker?

**Comment by bradfitz** [comment]
@ulrichSchreiner, I think you haven't updated the reflectutil code since Aug 9 2018's e4fd39d37c0d6f6dd0dfe5f42f0b0367bb7c0f55

This works for me.
